version: '3.4'

services:
  reza:
    image: ${DOCKER_REGISTRY-}reza
    build:
      context: .
      dockerfile: Reza/Dockerfile
    
    ports:
    - 5000:80
    - 5001:443
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
    - "5434:1433"
    volumes:
      - myapp:/var/opt/mssql
volumes:
  myapp:
    driver: local